"""Cross-principal authorization matrix builder and plan emitters (JSON/Markdown).

For every secured endpoint, generates a case for each (caller_role, owner_role)
pair where caller != owner. The expected verdict for foreign access is a deny
(HTTP 403 or 404); any 2xx observed during live replay indicates broken
object/function-level authorization (BOLA/IDOR/BFLA).
"""
from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

import yaml

from pentora.authzdiff.spec import Endpoint, SpecDiff, is_secured, iter_endpoints

EXPECTED_STATUS = (403, 404)


@dataclass(frozen=True)
class Role:
    name: str
    headers: dict[str, str]


@dataclass(frozen=True)
class AuthzCase:
    case_id: str
    method: str
    path: str
    caller: str
    owner: str
    expected_status: tuple[int, ...] = EXPECTED_STATUS


def load_roles(path: Path) -> list[Role]:
    """Load roles from YAML: ``{roles: [{name, headers}]}`` or a bare list."""
    data: Any = yaml.safe_load(path.read_text(encoding="utf-8"))
    if isinstance(data, dict):
        data = data.get("roles")
    if not isinstance(data, list) or not data:
        raise ValueError(f"{path} must define a non-empty list of roles")
    roles: list[Role] = []
    for entry in data:
        if not isinstance(entry, dict) or "name" not in entry:
            raise ValueError(f"Invalid role entry in {path}: {entry!r}")
        headers = {
            str(k): str(v)
            for k, v in (entry.get("headers") or {}).items()
        }
        roles.append(Role(name=str(entry["name"]), headers=headers))
    return roles


def build_matrix(
    spec: dict[str, Any],
    roles: list[Role],
    *,
    assume_secured: bool = False,
) -> list[AuthzCase]:
    """Generate cross-principal cases: n_secured * n_roles * (n_roles - 1)."""
    role_names = [r.name for r in roles]
    cases: list[AuthzCase] = []
    index = 0
    for ep in iter_endpoints(spec):
        if not is_secured(spec, ep, assume_secured=assume_secured):
            continue
        for owner in role_names:
            for caller in role_names:
                if caller == owner:
                    continue
                index += 1
                cases.append(
                    AuthzCase(
                        case_id=f"case-{index:04d}",
                        method=ep.method.upper(),
                        path=ep.path,
                        caller=caller,
                        owner=owner,
                    )
                )
    return cases


def render_plan_json(
    cases: list[AuthzCase],
    *,
    roles: list[Role] | None = None,
    diff: SpecDiff | None = None,
    results: list[dict[str, Any]] | None = None,
) -> str:
    """Render the review/replay plan as JSON."""
    plan: dict[str, Any] = {
        "tool": "pentora-authzdiff",
        "authorized_testing_only": True,
        "expected_verdict": {
            "outcome": "deny",
            "status": list(EXPECTED_STATUS),
            "meaning": (
                "2xx on a foreign-access case means broken authorization "
                "(BOLA/IDOR/BFLA) — verify before reporting."
            ),
        },
        "roles": [{"name": r.name, "headers": r.headers} for r in (roles or [])],
        "spec_diff": diff.to_dict() if diff else None,
        "total_cases": len(cases),
        "cases": [asdict(c) | {"expected_status": list(c.expected_status)} for c in cases],
        "results": results,
    }
    return json.dumps(plan, indent=2)


def render_plan_markdown(
    cases: list[AuthzCase],
    *,
    roles: list[Role] | None = None,
    diff: SpecDiff | None = None,
    results: list[dict[str, Any]] | None = None,
) -> str:
    """Render the plan as a human-reviewable Markdown report."""
    lines: list[str] = ["# Authorization Diff Plan", ""]
    lines.append("Generated by `pentora authzdiff`. Authorized testing only.")
    lines.append("")
    lines.append(
        f"**Expected verdict:** deny (`{'/'.join(str(s) for s in EXPECTED_STATUS)}`) "
        "for every case. A 2xx on foreign access is a potential BOLA/IDOR finding."
    )
    lines.append("")

    if diff is not None:
        lines += _diff_section(diff)

    if roles:
        lines += ["## Roles", "", "| Role | Headers |", "|------|---------|"]
        for r in roles:
            rendered = ", ".join(f"`{k}: {v}`" for k, v in r.headers.items()) or "—"
            lines.append(f"| {r.name} | {rendered} |")
        lines.append("")

    lines += [
        f"## Cases ({len(cases)})",
        "",
        "| # | Case ID | Method | Path | Caller | Owner | Expected |",
        "|---|---------|--------|------|--------|-------|----------|",
    ]
    for i, c in enumerate(cases, start=1):
        expected = "/".join(str(s) for s in c.expected_status)
        lines.append(
            f"| {i} | {c.case_id} | {c.method} | `{c.path}` | {c.caller} | {c.owner} "
            f"| {expected} |"
        )

    if results is not None:
        lines += ["", "## Live Replay Results", ""]
        lines.append(
            "| Case ID | Method | Path | Caller | Status | Control | Verdict |",
        )
        lines.append("|---------|--------|------|--------|--------|---------|---------|")
        critical = sum(1 for row in results if row["verdict"] == "critical_finding")
        denied = sum(1 for row in results if row["verdict"] == "expected_deny")
        inconclusive = len(results) - critical - denied
        for row in results:
            lines.append(_result_row(row))
        lines += [
            "",
            f"**Summary:** {critical} critical finding(s), {denied} expected deny, "
            f"{inconclusive} inconclusive.",
        ]
        if critical:
            lines.append("")
            lines.append(
                "> CRITICAL: 2xx responses above indicate principals accessing "
                "resources they do not own."
            )

    return "\n".join(lines) + "\n"


def _result_row(r: dict[str, Any]) -> str:
    verdict = str(r["verdict"])
    marker = {"critical_finding": "**CRITICAL**", "expected_deny": "deny"}.get(verdict, verdict)
    return (
        f"| {r['case_id']} | {r['method']} | `{r['path']}` | {r['caller']} "
        f"| {r['status_code']} | {r['control_status']} | {marker} |"
    )


def _diff_section(diff: SpecDiff) -> list[str]:
    lines = ["## Spec Diff (old → current)", ""]
    lines.append(f"- Added endpoints: {len(diff.added_endpoints)}")
    lines.append(f"- Removed endpoints: {len(diff.removed_endpoints)}")
    lines.append(f"- Parameter changes: {len(diff.param_changes)}")
    if diff.added_endpoints or diff.removed_endpoints or diff.param_changes:
        lines += ["", "| Change | Detail |", "|--------|--------|"]
        for e in diff.added_endpoints:
            lines.append(f"| added | `{e.method.upper()} {e.path}` |")
        for e in diff.removed_endpoints:
            lines.append(f"| removed | `{e.method.upper()} {e.path}` |")
        for pc in diff.param_changes:
            detail = ", ".join(filter(None, (
                f"added: {', '.join(pc.added_params)}" if pc.added_params else "",
                f"removed: {', '.join(pc.removed_params)}" if pc.removed_params else "",
                f"now required: {', '.join(pc.now_required)}" if pc.now_required else "",
            )))
            lines.append(f"| params | `{pc.method.upper()} {pc.path}` — {detail} |")
    lines.append("")
    return lines


def endpoints_from_cases(cases: list[AuthzCase]) -> list[Endpoint]:
    """Unique endpoints referenced by the given cases (helper for tooling)."""
    seen: dict[tuple[str, str], Endpoint] = {}
    for c in cases:
        seen.setdefault((c.path, c.method.lower()), Endpoint(c.path, c.method.lower()))
    return list(seen.values())
